# Generated by Django 4.0.7 on 2022-12-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isStaff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='isSuperuser',
            field=models.BooleanField(default=False),
        ),
    ]
