# Generated by Django 4.0.7 on 2023-01-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('date', models.DateField(null=True, verbose_name='')),
                ('house_type', models.CharField(max_length=200)),
                ('heating', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('floor', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=200)),
                ('price', models.CharField(blank=True, max_length=200)),
                ('price_month', models.CharField(blank=True, max_length=200)),
                ('price_year', models.CharField(blank=True, max_length=200)),
                ('maintenance_fee', models.CharField(max_length=200)),
                ('loan_repayment', models.CharField(max_length=200)),
                ('utility_bill', models.CharField(max_length=200)),
                ('structure', models.CharField(max_length=200)),
                ('desc', models.TextField()),
            ],
        ),
    ]
