# Generated by Django 4.0.7 on 2023-01-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='registrant',
            field=models.EmailField(default='admin', max_length=254, unique=True, verbose_name='이메일 주소'),
        ),
    ]
