# Generated by Django 4.0.7 on 2023-01-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_land_registrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='registrant',
            field=models.EmailField(default='admin', max_length=254, verbose_name='이메일 주소'),
        ),
    ]
