# Generated by Django 4.0.7 on 2023-01-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0003_alter_land_registrant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('date', models.DateField(null=True, verbose_name='')),
                ('house_type', models.CharField(max_length=200)),
                ('heating', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('floor', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=200)),
                ('price', models.CharField(blank=True, max_length=200)),
                ('price_month', models.CharField(blank=True, max_length=200)),
                ('price_year', models.CharField(blank=True, max_length=200)),
                ('maintenance_fee', models.CharField(max_length=200)),
                ('loan_repayment', models.CharField(max_length=200)),
                ('utility_bill', models.CharField(max_length=200)),
                ('structure', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('registrant', models.EmailField(max_length=254, verbose_name='이메일 주소')),
            ],
        ),
        migrations.DeleteModel(
            name='Land',
        ),
    ]
