export const LAND_REGISTER_REQUEST = 'LAND_REGISTER_REQUEST';
export const LAND_REGISTER_SUCCESS = 'LAND_REGISTER_SUCCESS';
export const LAND_REGISTER_FAIL = 'LAND_REGISTER_FAIL';
export const LAND_REGISTER_RESET = 'LAND_REGISTER_RESET';
